name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in dockerhub
      run:  echo "${{ secrets.DOCKERHUB_MKOKKONIDIS }}" | docker login -u m.kokkonidis --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag csbdashboard:3.3.40 
    - name: Push image to dockerhub
      run: docker push csbdashboard:3.3.40 
      
