name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in dockerhub
      run:  echo "${{ secrets.DOCKERHUB_MKOKKONIDIS }}" | docker login -u mkokkonidis --password-stdin
    - name: Build the docker image
      run: docker build . --file Dockerfile --tag mkokkonidis/csbdashboard:4.0.0 
    - name: Push image to dockerhub
      run: docker push mkokkonidis/csbdashboard:4.0.0
      
